// Generates data/sources.js from research/sources.json (written by tools/ledger.mjs).
//   node tools/build-sources.mjs
// Each source keeps the stable id the ledger assigned; `unverified: true` marks sources whose
// claims could not be independently re-opened by the fact-checkers.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { SOURCE_OVERRIDES } from './source-overrides.mjs';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const sources = JSON.parse(readFileSync(`${ROOT}research/sources.json`, 'utf8'));
const claims = new Map(JSON.parse(readFileSync(`${ROOT}research/claims.json`, 'utf8')).map(c => [c.id, c]));

const out = {};
const drop = new Set(SOURCE_OVERRIDES.drop || []);
for (const s of sources.sort((a, b) => a.id.localeCompare(b.id))) {
  if (drop.has(s.id)) continue;
  const users = s.usedBy.map(id => claims.get(id)).filter(Boolean);
  // Dates must be YYYY, YYYY-MM or YYYY-MM-DD. Researchers sometimes recorded "accessed 2026-10-07"
  // or "2026-07-30 (data last updated; accessed ...)": keep the first date as `date` (publication or
  // data-update date when given, else the access date) and the rest as a short `dateNote`.
  const raw = String(s.date || '');
  const m = raw.match(/\d{4}-\d{2}-\d{2}|\d{4}-\d{2}|\d{4}/);
  const isAccessOnly = /^(undated\s*)?\(?accessed/i.test(raw.trim()) || /^\d{4}-\d{2}-\d{2} \(accessed\)$/.test(raw.trim());
  const dateNote = raw === (m && m[0]) ? undefined : (isAccessOnly ? 'accessed' : raw.replace(m ? m[0] : '', '').replace(/^[\s(;]+|[\s);]+$/g, '').replace(/\s+/g, ' ') || undefined);
  out[s.id] = {
    title: s.title,
    publisher: s.publisher,
    url: s.url,
    date: m ? m[0] : '',
    ...(dateNote ? { dateNote } : {}),
    type: s.type,
    ...(users.length && users.every(c => c.unverified) ? { unverified: true } : {}),
    // tools/source-overrides.mjs: corrected titles, withheld links (see docs/decisions/fix.md)
    ...(SOURCE_OVERRIDES.patch?.[s.id] || {}),
  };
}
const body = `// Generated by tools/build-sources.mjs from research/sources.json. Do not edit by hand:
// fix the ledger (research/) or tools/source-overrides.mjs and regenerate.
// Every source here backs at least one fact-checked claim in research/claims.json.
export const SOURCES = ${JSON.stringify(out, null, 2)};
`;
writeFileSync(`${ROOT}data/sources.js`, body);
console.log(`data/sources.js: ${Object.keys(out).length} sources (${Object.values(out).filter(s => s.unverified).length} unverified)`);
