// Generates data/sources.js from research/sources.json (written by tools/ledger.mjs).
//   node tools/build-sources.mjs
// Each source keeps the stable id the ledger assigned; `unverified: true` marks sources whose
// claims could not be independently re-opened by the fact-checkers.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const sources = JSON.parse(readFileSync(`${ROOT}research/sources.json`, 'utf8'));
const claims = new Map(JSON.parse(readFileSync(`${ROOT}research/claims.json`, 'utf8')).map(c => [c.id, c]));

const out = {};
for (const s of sources.sort((a, b) => a.id.localeCompare(b.id))) {
  const users = s.usedBy.map(id => claims.get(id)).filter(Boolean);
  out[s.id] = {
    title: s.title,
    publisher: s.publisher,
    url: s.url,
    date: s.date,
    type: s.type,
    ...(users.length && users.every(c => c.unverified) ? { unverified: true } : {}),
  };
}
const body = `// Generated by tools/build-sources.mjs from research/sources.json. Do not edit by hand:
// fix the ledger (research/) and regenerate.
// Every source here backs at least one fact-checked claim in research/claims.json.
export const SOURCES = ${JSON.stringify(out, null, 2)};
`;
writeFileSync(`${ROOT}data/sources.js`, body);
console.log(`data/sources.js: ${Object.keys(out).length} sources (${Object.values(out).filter(s => s.unverified).length} unverified)`);
